image: "ubuntu:20.10"

before_script:
  - apt-get update -qq && apt-get install -y -qq cmake bison gawk wget build-essential python3

build-cet:
  script: 
    - mkdir build-cet 
    - mkdir -p ./glibc-cet
    - cd build-cet && ../configure --prefix=/intravirt/glibc-cet/install --with-tls --without-selinux --disable-test --disable-nscd --disable-sanity-checks --disable-werror --enable-cet=permissive "CFLAGS=-gdwarf-2 -g3 -O2 -U_FORTIFY_SOURCE -Wno-unused-value" && make -j && make DESTDIR=$PWD/glibc-cet install -j
  artifacts:
    paths:
      - ./glibc-cet

build-nocet:
  script: 
    - mkdir build-nocet 
    - mkdir -p ./glibc-nocet
    - cd build-nocet && ../configure --prefix=/intravirt/glibc-nocet/install --with-tls --without-selinux --disable-test --disable-nscd --disable-sanity-checks --disable-werror "CFLAGS=-gdwarf-2 -g3 -O2 -U_FORTIFY_SOURCE -Wno-unused_Value" && make -j && make DESTDIR=$PWD/glibc-nocet install -j
  artifacts:
    paths:
      - ./glibc-nocet
